import { describe, it, expect } from 'vitest';
import { AnalogOsc, NoiseGen, type OscShape } from '../AnalogOsc';

const SR = 48000;

function render(
  osc: AnalogOsc, freq: number, shape: OscShape, n: number, pw = 0.5, drift = 0,
): Float32Array {
  const buf = new Float32Array(n);
  for (let i = 0; i < n; i++) buf[i] = osc.process(freq, shape, pw, drift);
  return buf;
}

/** Naive (non-band-limited) saw, as the aliasing baseline. */
function naiveSaw(freq: number, n: number): Float32Array {
  const buf = new Float32Array(n);
  let phase = 0;
  for (let i = 0; i < n; i++) {
    phase += freq / SR;
    phase -= Math.floor(phase);
    buf[i] = 2 * phase - 1;
  }
  return buf;
}

/**
 * Magnitude at one frequency, by correlating against a complex exponential
 * generated by incremental rotation (no per-sample trig calls).
 */
function magnitudeAt(buf: Float32Array, freq: number): number {
  const w = (2 * Math.PI * freq) / SR;
  const c = Math.cos(w), s = Math.sin(w);
  let cr = 1, ci = 0, re = 0, im = 0;
  for (let i = 0; i < buf.length; i++) {
    re += buf[i] * cr;
    im -= buf[i] * ci;
    const t = cr * c - ci * s;
    ci = cr * s + ci * c;
    cr = t;
  }
  return Math.hypot(re, im) / buf.length;
}

/**
 * The frequencies where a saw's above-Nyquist harmonics fold back to.
 *
 * Probing an arbitrary grid does not work: for a periodic signal all energy —
 * aliased included — sits on a discrete grid, so a mismatched probe set
 * measures silence for both a clean and a filthy oscillator.
 */
function aliasProbeFreqs(f0: number): number[] {
  const out = new Set<number>();
  for (let n = Math.ceil(SR / 2 / f0) + 1; n <= 80; n++) {
    const raw = n * f0;
    const folded = Math.abs(raw - Math.round(raw / SR) * SR);
    if (folded < 60 || folded > SR / 2 - 60) continue;
    // Skip folds that land on a genuine harmonic, where the two are inseparable.
    if (Math.abs(folded - Math.round(folded / f0) * f0) < 30) continue;
    out.add(Math.round(folded));
  }
  return [...out];
}

/** Total energy sitting at aliased-partial frequencies. */
function aliasEnergy(buf: Float32Array, f0: number): number {
  return aliasProbeFreqs(f0).reduce((sum, f) => sum + magnitudeAt(buf, f) ** 2, 0);
}

function zeroCrossFreq(buf: Float32Array): number {
  let crossings = 0;
  for (let i = 1; i < buf.length; i++) {
    if (buf[i - 1] < 0 && buf[i] >= 0) crossings++;
  }
  return crossings / (buf.length / SR);
}

const mean = (b: Float32Array) => b.reduce((s, v) => s + v, 0) / b.length;

describe('AnalogOsc', () => {
  it('runs at the requested frequency', () => {
    for (const freq of [55, 220, 440, 1760]) {
      const buf = render(new AnalogOsc(SR, false), freq, 'sawtooth', SR);
      expect(zeroCrossFreq(buf)).toBeCloseTo(freq, 0);
    }
  });

  it('stays within range for every shape', () => {
    for (const shape of ['sawtooth', 'pulse', 'triangle', 'sine'] as OscShape[]) {
      const buf = render(new AnalogOsc(SR, false), 440, shape, SR / 4);
      for (const v of buf) {
        expect(Number.isFinite(v), shape).toBe(true);
        expect(Math.abs(v), shape).toBeLessThan(1.6);
      }
    }
  });

  it('aliases far less than a naive saw', () => {
    // The whole point of PolyBLEP. At a high fundamental a naive wave folds a
    // lot of energy back below Nyquist as inharmonic tones.
    const freq = 2200; // exactly 2200 cycles in the 1s buffer — no leakage
    const blep = render(new AnalogOsc(SR, false), freq, 'sawtooth', SR);
    const naive = naiveSaw(freq, SR);
    const reduction = aliasEnergy(blep, freq) / aliasEnergy(naive, freq);
    expect(reduction).toBeLessThan(0.1); // measured ~0.02, i.e. ~50x cleaner
  });

  it('puts most saw energy in the fundamental', () => {
    const freq = 440;
    const buf = render(new AnalogOsc(SR, false), freq, 'sawtooth', SR);
    expect(magnitudeAt(buf, freq)).toBeGreaterThan(magnitudeAt(buf, freq * 2));
    expect(magnitudeAt(buf, freq * 2)).toBeGreaterThan(magnitudeAt(buf, freq * 4));
  });

  it('changes pulse duty cycle with pulseWidth', () => {
    const dutyOf = (pw: number) => {
      const buf = render(new AnalogOsc(SR, false), 220, 'pulse', SR, pw);
      let high = 0;
      for (const v of buf) if (v > 0) high++;
      return high / buf.length;
    };
    expect(dutyOf(0.25)).toBeCloseTo(0.25, 1);
    expect(dutyOf(0.5)).toBeCloseTo(0.5, 1);
    expect(dutyOf(0.75)).toBeCloseTo(0.75, 1);
  });

  it('keeps a square pulse near zero DC', () => {
    const buf = render(new AnalogOsc(SR, false), 220, 'pulse', SR, 0.5);
    expect(Math.abs(mean(buf))).toBeLessThan(0.05);
  });

  it('produces a triangle with far weaker harmonics than a saw', () => {
    const freq = 440;
    const tri = render(new AnalogOsc(SR, false), freq, 'triangle', SR);
    const saw = render(new AnalogOsc(SR, false), freq, 'sawtooth', SR);
    const triRatio = magnitudeAt(tri, freq * 3) / magnitudeAt(tri, freq);
    const sawRatio = magnitudeAt(saw, freq * 3) / magnitudeAt(saw, freq);
    expect(triRatio).toBeLessThan(sawRatio);
  });

  it('starts at a random phase by default', () => {
    const first = Array.from({ length: 12 }, () => new AnalogOsc(SR).process(440, 'sawtooth'));
    // Phase-coherent oscillators would all emit the same first sample.
    expect(new Set(first.map(v => v.toFixed(4))).size).toBeGreaterThan(1);
  });

  it('starts deterministically when random phase is off', () => {
    const a = new AnalogOsc(SR, false).process(440, 'sawtooth');
    const b = new AnalogOsc(SR, false).process(440, 'sawtooth');
    expect(a).toBeCloseTo(b, 10);
  });

  it('handles negative frequency without breaking', () => {
    // Deep FM drives frequency through zero; the phase should run backwards
    // rather than produce NaN.
    const buf = render(new AnalogOsc(SR, false), -440, 'sawtooth', SR);
    for (const v of buf) expect(Number.isFinite(v)).toBe(true);
    // Same rate, opposite direction. Tolerance is one crossing: a descending
    // ramp can straddle the buffer edge differently to an ascending one.
    expect(Math.abs(zeroCrossFreq(buf) - 440)).toBeLessThanOrEqual(1);
  });

  it('handles zero frequency', () => {
    const buf = render(new AnalogOsc(SR, false), 0, 'sawtooth', 512);
    for (const v of buf) expect(Number.isFinite(v)).toBe(true);
  });

  it('drift detunes the oscillator without destabilising it', () => {
    const buf = render(new AnalogOsc(SR, false), 440, 'sawtooth', SR, 0.5, 1);
    for (const v of buf) expect(Number.isFinite(v)).toBe(true);
    // Still recognisably 440, just not exactly.
    expect(zeroCrossFreq(buf)).toBeGreaterThan(420);
    expect(zeroCrossFreq(buf)).toBeLessThan(460);
  });
});

describe('AnalogOsc hard sync', () => {
  it('resets phase on a rising zero-crossing', () => {
    const osc = new AnalogOsc(SR, false);
    for (let i = 0; i < 100; i++) osc.process(440, 'sawtooth');
    const beforeReset = osc.process(440, 'sawtooth');
    expect(beforeReset).toBeGreaterThan(-0.9); // well into the ramp

    expect(osc.processSync(-1)).toBe(false);
    expect(osc.processSync(1)).toBe(true);     // rising edge
    const afterReset = osc.process(440, 'sawtooth');
    expect(afterReset).toBeLessThan(-0.9);     // back to the start of the ramp
  });

  it('only triggers on the rising edge, not while held high', () => {
    const osc = new AnalogOsc(SR, false);
    expect(osc.processSync(1)).toBe(true);
    expect(osc.processSync(1)).toBe(false);
    expect(osc.processSync(0.5)).toBe(false);
    expect(osc.processSync(-1)).toBe(false);
    expect(osc.processSync(1)).toBe(true);
  });

  it('makes the synced oscillator take the master pitch', () => {
    // Classic hard sync: slave restarts every master cycle, so the perceived
    // pitch follows the master while timbre follows the slave's own frequency.
    const master = new AnalogOsc(SR, false);
    const slave = new AnalogOsc(SR, false);
    const masterFreq = 220;
    const buf = new Float32Array(SR);
    for (let i = 0; i < buf.length; i++) {
      const m = master.process(masterFreq, 'sawtooth');
      slave.processSync(m > 0 ? 1 : -1);
      buf[i] = slave.process(masterFreq * 2.7, 'sawtooth');
    }
    for (const v of buf) expect(Number.isFinite(v)).toBe(true);
    expect(magnitudeAt(buf, masterFreq)).toBeGreaterThan(0);
  });
});

describe('NoiseGen', () => {
  it('produces white noise in range with near-zero mean', () => {
    const g = new NoiseGen();
    const buf = new Float32Array(SR);
    for (let i = 0; i < buf.length; i++) buf[i] = g.white();
    for (const v of buf) expect(Math.abs(v)).toBeLessThanOrEqual(1);
    expect(Math.abs(mean(buf))).toBeLessThan(0.02);
  });

  it('produces pink noise weighted towards low frequencies', () => {
    const g = new NoiseGen();
    const buf = new Float32Array(SR);
    for (let i = 0; i < buf.length; i++) buf[i] = g.pink();
    for (const v of buf) expect(Number.isFinite(v)).toBe(true);
    // −3 dB/octave means substantially more energy low than high.
    const low = magnitudeAt(buf, 200);
    const high = magnitudeAt(buf, 8000);
    expect(low).toBeGreaterThan(high);
  });
});
